// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB14CbuMOa8g5GenW8UbvKDI3qBw9CcuaE',
    appId: '1:890598745016:android:cc13057b0a83fbe180e54d',
    messagingSenderId: '890598745016',
    projectId: 'ipoh-mobile-app',
    storageBucket: 'ipoh-mobile-app.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTqQdC5xd-LifeBzEkPDbY7rXM5RLUIXQ',
    appId: '1:890598745016:web:c04221ea10203ccb80e54d',
    messagingSenderId: '890598745016',
    projectId: 'ipoh-mobile-app',
    authDomain: 'ipoh-mobile-app.firebaseapp.com',
    storageBucket: 'ipoh-mobile-app.appspot.com',
    measurementId: 'G-7T79NZP3NM',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzkOYjRizNnNoQ7q1O5EK7D8RNvMTTR4U',
    appId: '1:890598745016:ios:9f6cdc99c37bbe7180e54d',
    messagingSenderId: '890598745016',
    projectId: 'ipoh-mobile-app',
    storageBucket: 'ipoh-mobile-app.appspot.com',
    androidClientId: '890598745016-6gsp6avie3jvpqt7oc71qp8l7b7kb81n.apps.googleusercontent.com',
    iosClientId: '890598745016-0oqhl8htshlqd2iibbe9ds49vkpanaet.apps.googleusercontent.com',
    iosBundleId: 'my.gov.mbi.travel',
  );

}